// Schema for `margo.config.{ts,js,mjs,json}` — committed to the repo,
// picks which storage mode the dev plugin runs in.
//
// Two modes:
//
//   - standalone — solo workspace, "me + AI on my machine." All comment
//     state lives at `~/.margo/standalone/<id>/`. No host, no sign-in,
//     no project tree footprint, no git operations. The `id` field is a
//     UUID generated by `margo init` so two repos on the same machine
//     never collide and moving the repo doesn't lose history.
//
//   - server — team collaboration via a self-hostable margo-host. The
//     plugin proxies HTTP to the host and mirrors comments into a local
//     cache at `~/.margo/cache/<host>/<project>/`. Auth via the bearer
//     token in `~/.margo/credentials.json` (populated by `margo login`).
//
// Neither mode puts anything under `.margo/` in the project tree —
// `margo.config.json` at the repo root is the entire committed
// footprint.

export type StorageMode = 'standalone' | 'server'

export interface MargoClientConfig {
  /** Required. `standalone` (default for `margo init`) or `server`. */
  storage: StorageMode
  /** Required when `storage === 'standalone'`. UUID generated at init
   *  time, kept stable in the committed config so the workspace's data
   *  dir under `~/.margo/standalone/<id>/` doesn't change when the repo
   *  is moved or cloned to a different path. */
  id?: string
  /** Required when `storage === 'server'`. */
  host?: string
  /** Required when `storage === 'server'`. Project slug on the host. */
  project?: string
  /** When `storage === 'server'` — optional auth-override block. Defaults
   *  to `{ type: 'bearer', tokenEnv: 'MARGO_TOKEN' }`. Only set to
   *  override the env-var name (e.g. a consultant juggling two hosts);
   *  the standard path is `margo login`, which writes to
   *  `~/.margo/credentials.json` and ignores this entirely. */
  auth?: {
    type?: 'bearer'
    tokenEnv?: string
  }
}

/** Type-safe authoring helper for margo.config.ts. Returns the input
 *  verbatim — the helper only exists so TypeScript can attach autocomplete
 *  and IntelliSense to user-authored config files. */
export function defineConfig(config: MargoClientConfig): MargoClientConfig {
  return config
}
